
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - binary_sensor: !include binary_sensors.yaml

lovelace:
  mode: storage
  dashboards:
    lovelace-pets:
      mode: yaml
      title: Pets
      icon: mdi:cat
      show_in_sidebar: true
      filename: pets.yaml
